### ISSUE TITLE
wrong argument type nil (expected String) when string begins with "www."

### ISSUE THREAD

**Issue by MaffooClock** [vmg/rinku#19]
I've been using Rinku for several months, and just recently, a problem popped up that I had not seen before.  I'm using Rinku on a particular text field which may or may not contain a URL.  All this time, the URLs have always started with `http://`, but recently, a user of this particular web application entered `www.hostname.tld`, and `Rinku.auto_link` started throwing exceptions:

```
wrong argument type nil (expected String)
  vendor/bundle/ruby/1.9.1/gems/rinku-1.5.1/lib/rails_rinku.rb:16:in `auto_link'
```

When I modified the string to start with `http://` or removed `www.`, the problem went away.

**Comment by swaathi** [comment]
I still get this error either with `https://` or `www`.

```
TypeError: wrong argument type nil (expected String)
	from (irb):21:in `auto_link'
	from (irb):21
```

This is what I'm trying to do, 

```Rinku.auto_link(text, mode=:all, link_attr=nil, skip_tags=nil) { |link| puts link }```

**Comment by bquorning** [comment]
Reproducible with Rinku v2.0.0:
```
>> gem "rinku", "2.0.0"
=> true
>> require "rinku"
=> true
>> Rinku.auto_link("google.com") { |link| puts link }
=> "google.com"
>> Rinku.auto_link("www.google.com") { |link| puts link }
www.google.com
TypeError: wrong argument type nil (expected String)
	from (irb):4:in `auto_link'
	from (irb):4
	from /Users/bquorning/.rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by kivikakk** [comment]
I can reproduce this too; looking into the cause.

**Comment by kivikakk** [comment]
Ah, this is actually the expected behaviour. From the README:

> `&block` is an optional block argument. If a block is passed, it will be yielded for each found link in the text, and its return value will be used instead of the name of the link. E.g.
> 
> ```ruby 
auto_link('Check it out at http://www.pokemon.com') do |url|
  "THE POKEMAN WEBSITEZ"
end
# => 'Check it out at <a href="http://www.pokemon.com">THE POKEMAN WEBSITEZ</a>'
```

The block is never called in the `"google.com"` example because no autolinking has taken place. It's called in the `"www.google.com"` example, `puts` does its thing, then returns `nil` to Rinku, which is wanting a String.

If you want to use it this way (and ignore the result), you could return an empty string from the block:

```
>> Rinku.auto_link("www.google.com") { |link| puts link; "" }; nil
www.google.com
=> nil
```
