### ISSUE TITLE
target parameter

### ISSUE THREAD

**Issue by meandkareem** [vmg/rinku#22]
undefined method `each_pair' for "target='_blank'":String 

on rails 3.2.5

**Comment by somazx** [comment]
Yes please to updating the documentation.

**Comment by AdamDenoon** [comment]
Again, please update the documentation

**Comment by kivikakk** [comment]
The docs refer to the base Rinku usage, which has not changed:

```
>> gem 'rinku', '2.0.1'
=> true
>> require 'rinku'
=> true
>> Rinku.auto_link('http://www.pokemon.com', :all, 'target="_blank"')
=> "<a href=\"http://www.pokemon.com\" target=\"_blank\">http://www.pokemon.com</a>"
```

They also note that the monkey-patched Rails method mimics the original (i.e. per the Rails docs). I'll add a note to the README with a Rails specific example so this is harder to mistake.
