### ISSUE TITLE
Extract_URLs method

### ISSUE THREAD

**Issue by paladini** [vmg/rinku#33]
Hello guys,

I want suggest a thing that can improve a lot the "Rinku" gem. I try to find this in this gem, but I think it doesn't exist yet. 

What you think about add a method to extract urls, like Twitter-Text gem does with "extract_urls"? It will be very useful and can increment the usage of this gem.

Thanks for attention,
A hug, Fernando P.

**Comment by kivikakk** [comment]
I think this is a bit out of scope of Rinku. You can approximate this usage by passing a block to `Rinku.auto_link`, but in general you might find a different library is more appropriate for this use case.
