### ISSUE TITLE
Segmentation fault when passing in a partial `a href` tag

### ISSUE THREAD

**Issue by tomsabin** [vmg/rinku#35]
Providing the `auto_link` method with a partial `a href` tag (possibly due to a truncated string) causes a segmentation fault.

e.g.
```RUBY
> Rinku.auto_link("<a href='http://github.com/'>gith...")
(irb):1: [BUG] Segmentation fault
ruby 1.8.7 (2013-06-27 patchlevel 374) [i686-darwin12.4.0]

Abort trap: 6
```

**Comment by kivikakk** [comment]
As 1.8.x is retired, it is definitely not supported by rinku; sorry. 😞
