### ISSUE TITLE
Force string

### ISSUE THREAD

**Issue by harmdewit** [vmg/rinku#36]
When using autolink for user generated content the content may be `nil`. This returns an error:

```ruby
Rinku.auto_link(nil) # => TypeError: wrong argument type nil (expected String)
```

Maybe the argument could be forced to string with `to_s`.

**Comment by kivikakk** [comment]
This could be getting dangerously close to garbage-in-garbage-out; it's preferable that you deal with `nil` in an application-specific manner rather than relying on Rinku to coerce it to the empty string for you.

**Comment by harmdewit** [comment]
Yeah... I don't know why i made this an issue 3 years ago...

**Comment by kivikakk** [comment]
Haha, I'm just cleaning out old issues :)
