### ISSUE TITLE
Cannot find such file rinku.so

### ISSUE THREAD

**Issue by ezuhaib** [vmg/rinku#40]
rinku is being installed in my app as a dependency of wikicloth gem. However when I run my application, it says:

    `require': cannot load such file -- rinku.so (LoadError)

I opened the gem and could not find any such file either. What is the issue?

**Comment by kivikakk** [comment]
Are you still having this trouble? I'll close this issue assuming that this is (long) gone, given the date, but if you're still having issues, please feel free to open another issue!
