### ISSUE TITLE
Way to link URLs with no http:// or www.

### ISSUE THREAD

**Issue by aguynamedben** [vmg/rinku#41]
Nice job on this library.  I'm wondering if there is a config option I'm missing or something to convert URLs without a leading http:// or www.

For example, convert

```
Let's go to google.com
```

to

```
Let's go to <a href="http://google.com">google.com</a>
```

**Comment by Bertg** [comment]
:+1: 

Other link processors (embedly, iOS/OSX data detectors) do very similar things. It seems these work with a predefined list of TLDs they recognise. 

A naive example of what could work as a detector:

```ruby
/[a-z0-9-_\.]\.(com|net|info|net)/
```

**Comment by kivikakk** [comment]
This is out-of-scope for rinku, unfortunately! Using a TLD whitelist isn't going to be much fun, but without one the chance of false positives is just too high.
