### ISSUE TITLE
Can't compile 2.0.0 on windows

### ISSUE THREAD

**Issue by ahorek** [vmg/rinku#53]
there was no problem with the previous version 1.7.3

C:\Ruby21-x64\devkit>gem update rinku
Updating installed gems
Updating rinku
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing rinku:
        ERROR: Failed to build gem native extension.

    C:/Ruby21-x64/bin/ruby.exe extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating rinku-x64-mingw32.def
      0 [main] sh 4768 fork_copy: linked dll data/bss pass 0 failed, 0x6E8000..0x6E8AD8, done 0, windows pid 256, Win32 error 487
/bin/sh: fork: Resource temporarily unavailable
make: *** [rinku-x64-mingw32.def] Error 128

make failed, exit code 2

**Comment by vmg** [comment]
Hm, I'm really unsure this is related to changes in the code. It looks like your MinGW Make is failing to fork. Maybe resource exhaustion?

**Comment by ahorek** [comment]
My devkit was broken, this can be closed, thanks.

**Comment by vmg** [comment]
I figured. 😄
