### ISSUE TITLE
auto_link does not recognise localhost:3000 links

### ISSUE THREAD

**Issue by wakiki** [vmg/rinku#7]
Hi, in Rails we often use addresses with localhost:3000 in development. Rinku doesn't seem to recognise these as links.

eg. http://localhost:3000/xyz

Can this be included so it turns them into links too?

Thanks

Steve

**Comment by davidhq** [comment]
`Rinku.short_domains` doesn't exist anymore? So how is this done nowadays?

**Comment by kivikakk** [comment]
`Rinku.short_domains` is now a flag which can be passed to `Rinku.auto_link`:

```
>> Rinku.auto_link('http://localhost:3000/a', nil, nil, nil, Rinku::AUTOLINK_SHORT_DOMAINS)
=> "<a href=\"http://localhost:3000/a\">http://localhost:3000/a</a>"
```

Not catching "github.com" without a preceding `http://` or `www.` is intentional.
