### ISSUE TITLE
tag_options error on Rails 5.1.1

### ISSUE THREAD

**Issue by Floppy** [vmg/rinku#70]
I've not dug into it yet, but I suspect that `tag_options` has been deprecated. I'm getting `undefined method 'tag_options' for #<#<Class:0x007f8d2d15d3c8>:0x007f8d2d2f6e00>` inside auto_link after upgrading from rails 5.0. This is rinku `2.0.2`.

**Comment by Floppy** [comment]
Yep, it's moved inside the `tag_builder` object inside the helper. I resolved it in my app by adding this helper:

```
  def tag_options(options, escape = true)
    tag_builder.tag_options(options, escape)
  end
```

I think this is available in Rails 5 and up.

**Comment by tisba** [comment]
Nice! Are you planning on cutting a release soon? That would be awesome!

**Comment by kivikakk** [comment]
I'll do so tomorrow! 👍

**Comment by kivikakk** [comment]
2.0.4 is released!
